spring:
  dataSource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/xu?useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&zeroDateTimeBehavior=convertToNull&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  batch:
    initialize-schema: always
  main:
    allow-bean-definition-overriding: true #当多个bean遇到同样名字的时候，是否允许覆盖注册
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    jedis:
      pool:
        max-active: 32
        max-wait: -1
        max-idle: 8
        min-idle: 0
    redisson:
      config: classpath:redisson.yml
server:
  port: 8110
  servlet:
    context-path: /api/all
  tomcat:
    uri-encoding: UTF-8
    max-connections: 2000
    max-threads: 1000
    min-spare-threads: 64
zookeeper:
  address: 127.0.0.1:2181
  session-timeout: 4000
  connection-timeout-ms: 3000
logging:
  config: classpath:logback.xml